import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Menubar,MenubarContent,MenubarMenu,MenubarTrigger,MenubarItem,MenubarShortcut,MenubarSeparator } from "@/components/ui/menubar";
import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogTitle, AlertDialogHeader, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

import MainMenu from "@/components/MainMenu";
import Note from "@/components/Note";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cards = [
    {title: "Untitled Note 1", timestamp: "02/17/24 7:34pm"},
    {title: "Untitled Note 2", timestamp: "02/17/24 7:34pm"},
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-[30%_70%] fixed w-full min-h-screen bg-zinc-900 text-zinc-50">
          <div className="border-r-[1px] border-zinc-600 grid grid-rows-[80px]">
            <MainMenu />
            <div className="w-full flex flex-col p-5 gap-2">
              {
                  cards.map(card => {
                      return <Note title={card.title} timestamp={card.timestamp} key={card.title}/>
                  })
              }
            </div>
          </div>

          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
