import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";

import MainMenu from "@/components/MainMenu";
import Note from "@/components/Note";

import { getServerSession } from "next-auth";
import { SessionProvider } from 'next-auth/react'
import { authOptions } from "../../prisma/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "markme",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)

  const cards = [
    {title: "Untitled Note 1", timestamp: "02/17/24 7:34pm"},
    {title: "Untitled Note 2", timestamp: "02/17/24 7:34pm"},
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        <main className="grid grid-cols-[30%_70%] fixed w-full min-h-screen bg-zinc-900 text-zinc-50">
          <div className="border-r-[1px] border-zinc-600 grid grid-rows-[80px]">
            <MainMenu session={session}/>
            <div className="w-full flex flex-col p-5 gap-2">
              {/* {
                  cards.map(card => {
                      return <Note title={card.title} timestamp={card.timestamp} key={card.title}/>
                  })
              } */}
            </div>
          </div>

          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
